{
 "title": "RED metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "${service_name}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service_name" },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_request_duration_seconds_count{service_name=~\"${service_name}\"}[$__rate_interval]))",
     "legendFormat": "requests/second"
    }
   ]
  },
  {
   "title": "Error Rate (product-service)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=~\"${service_name}\", http_response_status_code=~\"5..\"}[$__rate_interval])) OR on() vector(0) / sum(rate(http_server_request_duration_seconds_count{service_name=~\"${service_name}\"}[$__rate_interval]))",
     "legendFormat": "percentage of HTTP 5xx status codes"
    }
   ]
  },
  {
   "title": "Duration (product-service)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_server_request_duration_seconds_bucket{service_name=~\"${service_name}\"}[$__rate_interval])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_request_duration_seconds_bucket{service_name=~\"${service_name}\"}[$__rate_interval])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.98, sum by (le) (rate(http_server_request_duration_seconds_bucket{service_name=~\"${service_name}\"}[$__rate_interval])))",
     "legendFormat": "98th percentile"
    }
   ]
  }
 ]
}