apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/grafana/provisioning
          name: grafana-provisioning
        - mountPath: /mnt
          name: grafana-dashboards
      volumes:
      - name: grafana-provisioning
        configMap:
          name: grafana-provisioning
          items:
          - key: grafana-datasources.yaml
            path: datasources/grafana-datasources.yaml
          - key: grafana-dashboards.yaml
            path: dashboards/grafana-dashboards.yaml
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
